
name: Release tagged build

on:
  push:
    tags: [ 'v1.0.6' ]

permissions:
  contents: write

jobs:
  release-tags:
    runs-on: windows-latest
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 32
          submodules: recursive

      - name: Set up JDK versions
        uses: actions/setup-java@v5
        with:
          java-version: |
            8
            17
            21
            25
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: https://gradle.com/terms-of-service
          build-scan-terms-of-use-agree: 'yes'
          validate-wrappers: true

      - name: Build the mod
        shell: pwsh
        run: .\gradlew.bat clean build --no-configuration-cache --no-parallel '-Dorg.gradle.problems.report=false'

      - name: Release under current tag
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete $env:GITHUB_REF_NAME --yes 2>$null
          $assets = Get-ChildItem build/libs -Filter '*.jar' | ForEach-Object { $_.FullName }
          gh release create $env:GITHUB_REF_NAME `
            --title $env:GITHUB_REF_NAME `
            --notes "GTNH 2.8.4 maintenance release." `
            $assets
