
name: Release tagged build

on:
  push:
    tags: [ 'v1.0.6' ]

permissions:
  contents: write

jobs:
  release-tags:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 32
          submodules: recursive

      - name: Set up JDK versions
        uses: actions/setup-java@v5
        with:
          java-version: |
            8
            17
            21
            25
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: https://gradle.com/terms-of-service
          build-scan-terms-of-use-agree: 'yes'
          validate-wrappers: true

      - name: Build the mod
        run: |
          chmod +x gradlew
          ./gradlew --build-cache --info --stacktrace -PmavenPublishUrl='https://nexus.gtnewhorizons.com/repository/releases/' assemble

      - name: Release under current tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "${GITHUB_REF_NAME}" --yes || true
          gh release create "${GITHUB_REF_NAME}" \
            --title "${GITHUB_REF_NAME}" \
            --notes "GTNH 2.8.4 maintenance release." \
            ./build/libs/*.jar
